# yaml-language-server: $schema=../../infra-helm-charts/charts/generic-app/values.schema.json

environment: "prod"
version: "${COMMIT_SHA}"

deployments:
  - name: "join-sound-website"
    image: "${DOCKERHUB_USERNAME}/${DOCKERHUB_REPO}:${REPO_NAME}-prod"
    service:
      port: 8080
      targetPort: 8080
    ingress:
      subdomain: "join-sound"
    readinessProbe:
      httpGet:
        path: "/"
        port: 8080
