name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    uses: mocbotau/infra-workflows/.github/workflows/generic-deploy.yaml@v0.1.1
    with:
      event-name: ${{ github.event_name }}
      environment: "prod"
      repo-name: "mocbot-join-sound-uploader"
    secrets: inherit
