name: Helmfile Diff

on:
  pull_request:

jobs:
  helmfile-diff:
    uses: mocbotau/infra-workflows/.github/workflows/generic-helmfile-diff.yaml@v0.3.0
    with:
      environment: "prod"
    secrets: inherit

permissions:
  contents: read
  pull-requests: write
